Fix buffer issue on Windows 10
Solves this issue which was occurring on Windows but not Linux.

  File "C:\Users\user\Desktop\FindTheMag\libs\pyboinc\rpc_client.py", line 142, in get_project_status
    return [Project(**parse_generic(c)) for c in await self._request(req)]
  File "C:\Users\user\Desktop\FindTheMag\libs\pyboinc\rpc_client.py", line 78, in _request
    return await self._raw_client.request(req)
  File "C:\Users\user\Desktop\FindTheMag\libs\pyboinc\_raw_client.py", line 82, in request
    return await self.receive()
  File "C:\Users\user\Desktop\FindTheMag\libs\pyboinc\_raw_client.py", line 63, in receive
    buff = [await self._read()]
  File "C:\Users\user\Desktop\FindTheMag\libs\pyboinc\_raw_client.py", line 57, in _read
    return await self._reader.readuntil(separator=END_OF_MESSAGE)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\streams.py", line 620, in readuntil
    raise exceptions.LimitOverrunError(
asyncio.exceptions.LimitOverrunError: Separator is found, but chunk is longer than limit